/**
 * This class is generated by jOOQ
 */
package me.kieranwallbanks.barrymore.mysql;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Barrymore extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1325297899;

	/**
	 * The singleton instance of <code>barrymore</code>
	 */
	public static final Barrymore BARRYMORE = new Barrymore();

	/**
	 * No further instances allowed
	 */
	private Barrymore() {
		super("barrymore");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			me.kieranwallbanks.barrymore.mysql.tables.Users.USERS);
	}
}
