/**
 * This class is generated by jOOQ
 */
package me.kieranwallbanks.barrymore.mysql;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in barrymore
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table barrymore.users
	 */
	public static final me.kieranwallbanks.barrymore.mysql.tables.Users USERS = me.kieranwallbanks.barrymore.mysql.tables.Users.USERS;
}
