/**
 * This class is generated by jOOQ
 */
package me.kieranwallbanks.barrymore.mysql.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends org.jooq.impl.UpdatableRecordImpl<UsersRecord> implements org.jooq.Record6<Long, String, String, String, String, String> {

	private static final long serialVersionUID = 869533910;

	/**
	 * Setter for <code>barrymore.users.id</code>. 
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>barrymore.users.id</code>. 
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>barrymore.users.irc</code>. 
	 */
	public void setIrc(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>barrymore.users.irc</code>. 
	 */
	public String getIrc() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>barrymore.users.fbo</code>. 
	 */
	public void setFbo(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>barrymore.users.fbo</code>. 
	 */
	public String getFbo() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>barrymore.users.dbo_api</code>. 
	 */
	public void setDboApi(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>barrymore.users.dbo_api</code>. 
	 */
	public String getDboApi() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>barrymore.users.theme</code>. 
	 */
	public void setTheme(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>barrymore.users.theme</code>. 
	 */
	public String getTheme() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>barrymore.users.fbo_pass</code>. 
	 */
	public void setFboPass(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>barrymore.users.fbo_pass</code>. 
	 */
	public String getFboPass() {
		return (String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<Long, String, String, String, String, String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<Long, String, String, String, String, String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<Long> field1() {
		return me.kieranwallbanks.barrymore.mysql.tables.Users.USERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field2() {
		return me.kieranwallbanks.barrymore.mysql.tables.Users.USERS.IRC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field3() {
		return me.kieranwallbanks.barrymore.mysql.tables.Users.USERS.FBO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field4() {
		return me.kieranwallbanks.barrymore.mysql.tables.Users.USERS.DBO_API;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field5() {
		return me.kieranwallbanks.barrymore.mysql.tables.Users.USERS.THEME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<String> field6() {
		return me.kieranwallbanks.barrymore.mysql.tables.Users.USERS.FBO_PASS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getIrc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getFbo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getDboApi();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getTheme();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getFboPass();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersRecord
	 */
	public UsersRecord() {
		super(me.kieranwallbanks.barrymore.mysql.tables.Users.USERS);
	}
}
