/**
 * This class is generated by jOOQ
 */
package me.kieranwallbanks.barrymore.mysql.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends org.jooq.impl.TableImpl<me.kieranwallbanks.barrymore.mysql.tables.records.UsersRecord> {

	private static final long serialVersionUID = -1250397492;

	/**
	 * The singleton instance of <code>barrymore.users</code>
	 */
	public static final Users USERS = new Users();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<me.kieranwallbanks.barrymore.mysql.tables.records.UsersRecord> getRecordType() {
		return me.kieranwallbanks.barrymore.mysql.tables.records.UsersRecord.class;
	}

	/**
	 * The column <code>barrymore.users.id</code>. 
	 */
	public final org.jooq.TableField<me.kieranwallbanks.barrymore.mysql.tables.records.UsersRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>barrymore.users.irc</code>. 
	 */
	public final org.jooq.TableField<me.kieranwallbanks.barrymore.mysql.tables.records.UsersRecord, String> IRC = createField("irc", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>barrymore.users.fbo</code>. 
	 */
	public final org.jooq.TableField<me.kieranwallbanks.barrymore.mysql.tables.records.UsersRecord, String> FBO = createField("fbo", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>barrymore.users.dbo_api</code>. 
	 */
	public final org.jooq.TableField<me.kieranwallbanks.barrymore.mysql.tables.records.UsersRecord, String> DBO_API = createField("dbo_api", org.jooq.impl.SQLDataType.VARCHAR.length(512), this);

	/**
	 * The column <code>barrymore.users.theme</code>. 
	 */
	public final org.jooq.TableField<me.kieranwallbanks.barrymore.mysql.tables.records.UsersRecord, String> THEME = createField("theme", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>barrymore.users.fbo_pass</code>. 
	 */
	public final org.jooq.TableField<me.kieranwallbanks.barrymore.mysql.tables.records.UsersRecord, String> FBO_PASS = createField("fbo_pass", org.jooq.impl.SQLDataType.VARCHAR.length(512), this);

	/**
	 * Create a <code>barrymore.users</code> table reference
	 */
	public Users() {
		super("users", me.kieranwallbanks.barrymore.mysql.Barrymore.BARRYMORE);
	}

	/**
	 * Create an aliased <code>barrymore.users</code> table reference
	 */
	public Users(String alias) {
		super(alias, me.kieranwallbanks.barrymore.mysql.Barrymore.BARRYMORE, Users.USERS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<me.kieranwallbanks.barrymore.mysql.tables.records.UsersRecord, Long> getIdentity() {
		return me.kieranwallbanks.barrymore.mysql.Keys.IDENTITY_USERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<me.kieranwallbanks.barrymore.mysql.tables.records.UsersRecord> getPrimaryKey() {
		return me.kieranwallbanks.barrymore.mysql.Keys.KEY_USERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<me.kieranwallbanks.barrymore.mysql.tables.records.UsersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<me.kieranwallbanks.barrymore.mysql.tables.records.UsersRecord>>asList(me.kieranwallbanks.barrymore.mysql.Keys.KEY_USERS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Users as(String alias) {
		return new Users(alias);
	}
}
